image: Visual Studio 2017 RC

install: 
  - cmd: nuget install gitlink -SolutionDir %APPVEYOR_BUILD_FOLDER% -Verbosity quiet -ExcludeVersion -pre

nuget:
  disable_publish_on_pr: true
    
build_script:
  - cmd: msbuild xunit.devices.proj /t:GitVersion /p:Configuration=Release
  - cmd: msbuild xunit.devices.proj /t:CI /p:Configuration=Release
  

artifacts:
  - path: '*.nupkg'

test: off
  
deploy:
  provider: NuGet
  server: https://www.myget.org/F/xunit-xamarin/api/v2/package
  symbol_server: https://www.myget.org/F/xunit-xamarin/symbols/api/v2/package
  api_key:
    secure: w1p7TvDGit5RlN4XKLjDC12Kd43SQ5qwLgRGGXtjfHKX1Yf7ZAOYBW6pLUkPJFJ6
  artifact: /.*\.nupkg/
